# Generated by Django 4.0.6 on 2022-07-08 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_todo_options_alter_todo_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todo',
            new_name='TodoModel',
        ),
    ]
