# Generated by Django 4.0.6 on 2022-07-08 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_todo_todomodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TodoModel',
            new_name='Todo',
        ),
    ]
